[project]
name = "vcl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.11.26",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "wandb>=0.19.8",
]
